version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-oxygen
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - web-tests
  chrome:
    image: selenium/node-chrome-debug:3.141.59-oxygen
#    image: selenium/node-chrome:3.141.59-oxygen
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - web-tests
#  firefox:
#    image: selenium/node-firefox-debug:3.141.59-oxygen
#    image: selenium/node-firefox:3.141.59-oxygen
#    volumes:
#      - /dev/shm:/dev/shm
#    depends_on:
#      - selenium-hub
#    environment:
#      - HUB_HOST=selenium-hub
#      - HUB_PORT=4444
#    network:
#      - web-tests

networks:
  web-tests: